#my_meloman_homepage:
 #   path:     /
 #   defaults: { _controller: myMelomanBundle:Default:index }
login:
  path: /
  defaults: { _controller: myMelomanBundle:Login:login}

validate:
  path: /validate/
  defaults: { _controller: myMelomanBundle:Login:validate}

home:
  path: /home
  defaults: { _controller: myMelomanBundle:User:home }

logout:
  path: /logout
  defaults: { _controller: myMelomanBundle:Login:logout }

user_profile_edit:
  path: /user-profile/edit
  defaults: { _controller: myMelomanBundle:User:userEditProfile }

user_profile_page:
  path: /user-profile/show
  defaults: { _controller: myMelomanBundle:User:userProfilePage }

user_list:
  path: /user-list
  defaults: { _controller: myMelomanBundle:User:userList }

user_search:
  path: /user-search
  defaults: { _controller: myMelomanBundle:User:search }

create_userProfile:
  path: /create-userprofile
  defaults: { _controller: myMelomanBundle:User:createUserProfile }
  methods: [POST]

create_publication:
  path: /create-publication/new
  defaults: { _controller: myMelomanBundle:Publication:createPublication }

create_publication_from_spotify:
  path: /create-publication-spotify/new
  defaults: { _controller: myMelomanBundle:Publication:createPublicationFromSpotify }

delete_publication:
  path: /delete-publication/{id}
  defaults: { _controller: myMelomanBundle:Publication:deletePublication }

like_publication:
  path: /like/{id}
  defaults: { _controller: myMelomanBundle:Like:like}

dislike_publication:
  path: /dislike/{id}
  defaults: { _controller: myMelomanBundle:Like:dislike}

follow_user:
  path: /follow-user/{id}
  defaults: { _controller: myMelomanBundle:Follow:follow }

unfollow_user:
  path: /unfollow-user/{id}
  defaults: { _controller: myMelomanBundle:Follow:unfollow }

spotify_search_song:
  path: /spotify/search
  defaults: { _controller: myMelomanBundle:Spotify:searchSong }

