#my_meloman_homepage:
 #   path:     /
 #   defaults: { _controller: myMelomanBundle:Default:index }
login:
  path: /
  defaults: { _controller: myMelomanBundle:Login:login}

validate:
  path: /validate/
  defaults: { _controller: myMelomanBundle:Login:validate}

home:
  path: /home
  defaults: { _controller: myMelomanBundle:User:home }

logout:
  path: /logout
  defaults: { _controller: myMelomanBundle:Login:logout }

user_profile:
  path: /user-profile
  defaults: { _controller: myMelomanBundle:User:userProfile }

user_list:
  path: /user-list
  defaults: { _controller: myMelomanBundle:User:userList }

user_search:
  path: /user-search
  defaults: { _controller: myMelomanBundle:User:search }

create_userProfile:
  path: /create-userprofile
  defaults: { _controller: myMelomanBundle:User:createUserProfile }
  methods: [POST]

create_publication:
  path: /create-publication/new
  defaults: { _controller: myMelomanBundle:Publication:createPublication }

